"use client";
import React, { useState } from "react";

/**
 * ReportPanel.jsx
 * ───────────────
 * Collapsible radiology report panel for NeuroDL v2.0.
 *
 * Displays the LLM-generated report from Ollama in a structured,
 * monospace layout with colour-highlighted section labels.
 *
 * Props:
 *   report   (string | null) — raw report text from /predict response
 *   loading  (bool)          — true while /predict is in flight
 */

// Section headers we want to highlight in the report body
const SECTION_LABELS = ["EXAMINATION:", "DATE:", "SYSTEM:", "FINDINGS:", "IMPRESSION:", "DISCLAIMER:"];

const ReportPanel = ({ report, loading }) => {
  const [isOpen, setIsOpen] = useState(true);

  // ── Parse report text into highlighted segments ──────────────
  const renderReportBody = (text) => {
    if (!text) return null;

    const lines = text.split("\n");
    return lines.map((line, idx) => {
      const matchedLabel = SECTION_LABELS.find((label) =>
        line.trim().startsWith(label)
      );

      if (matchedLabel) {
        const rest = line.trim().slice(matchedLabel.length);
        return (
          <div key={idx}>
            <span className="report-section-label">{matchedLabel}</span>
            {rest && (
              <span style={{ color: "var(--color-text-secondary)" }}>{rest}</span>
            )}
          </div>
        );
      }

      // Empty line → spacer
      if (line.trim() === "") {
        return <div key={idx} style={{ height: "0.6rem" }} />;
      }

      return (
        <div key={idx} style={{ color: "var(--color-text-secondary)" }}>
          {line}
        </div>
      );
    });
  };

  return (
    <div className="report-panel fade-in">
      {/* ── Header (always visible, toggles body) ── */}
      <div
        className="report-header"
        onClick={() => setIsOpen((prev) => !prev)}
        role="button"
        aria-expanded={isOpen}
      >
        <div className="report-header-left">
          {/* Icon */}
          <div className="report-header-icon">
            <svg
              className="w-4 h-4"
              fill="none"
              stroke="currentColor"
              viewBox="0 0 24 24"
            >
              <path
                strokeLinecap="round"
                strokeLinejoin="round"
                strokeWidth={2}
                d="M9 12h6m-6 4h6m2 5H7a2 2 0 01-2-2V5a2 2 0 012-2h5.586a1 1 0 01.707.293l5.414 5.414a1 1 0 01.293.707V19a2 2 0 01-2 2z"
              />
            </svg>
          </div>

          <div>
            <h3>AI Radiology Report</h3>
            <p
              style={{
                fontSize: "0.8rem",
                color: "var(--color-text-light)",
                margin: 0,
                fontWeight: 400,
              }}
            >
              Generated by Ollama / llama3.1:8b — for research purposes only
            </p>
          </div>
        </div>

        {/* Chevron */}
        <svg
          className={`report-chevron ${isOpen ? "open" : ""}`}
          width="20"
          height="20"
          fill="none"
          stroke="currentColor"
          viewBox="0 0 24 24"
        >
          <path
            strokeLinecap="round"
            strokeLinejoin="round"
            strokeWidth={2}
            d="M19 9l-7 7-7-7"
          />
        </svg>
      </div>

      {/* ── Body ── */}
      {isOpen && (
        <>
          {/* Still loading */}
          {loading && (
            <div className="report-loading">
              <svg
                className="spinning"
                width="18"
                height="18"
                fill="none"
                stroke="currentColor"
                viewBox="0 0 24 24"
              >
                <path
                  strokeLinecap="round"
                  strokeLinejoin="round"
                  strokeWidth={2}
                  d="M4 4v5h.582m15.356 2A8.001 8.001 0 004.582 9m0 0H9m11 11v-5h-.581m0 0a8.003 8.003 0 01-15.357-2m15.357 2H15"
                />
              </svg>
              Generating radiology report via Ollama...
            </div>
          )}

          {/* Report available */}
          {!loading && report && (
            <div className="report-body">{renderReportBody(report)}</div>
          )}

          {/* Ollama unavailable */}
          {!loading && !report && (
            <div className="report-unavailable">
              <svg
                style={{ width: 40, height: 40, margin: "0 auto 12px", display: "block", opacity: 0.3 }}
                fill="none"
                stroke="currentColor"
                viewBox="0 0 24 24"
              >
                <path
                  strokeLinecap="round"
                  strokeLinejoin="round"
                  strokeWidth={2}
                  d="M12 9v2m0 4h.01m-6.938 4h13.856c1.54 0 2.502-1.667 1.732-3L13.732 4c-.77-1.333-2.694-1.333-3.464 0L3.34 16c-.77 1.333.192 3 1.732 3z"
                />
              </svg>
              <p style={{ margin: 0, fontSize: "0.9rem" }}>
                Report unavailable — Ollama may not be running.
              </p>
              <p style={{ margin: "4px 0 0", fontSize: "0.8rem", color: "var(--color-text-light)" }}>
                Run <code style={{ background: "#f0f0f0", padding: "2px 6px", borderRadius: 4 }}>ollama serve</code> and retry.
              </p>
            </div>
          )}
        </>
      )}
    </div>
  );
};

export default ReportPanel;