"""
model_performance_route.py
──────────────────────────
Add this route to app.py (before error handlers).
Serves the pre-computed model_performance.json generated by evaluate_models.py.

No auth required — model performance data is public.
"""

import json as _json   # rename to avoid conflict with flask.json

@app.route("/model-performance", methods=["GET"])
def model_performance():
    """
    Serve pre-computed evaluation metrics for the frontend charts.
    Run evaluate_models.py first to generate the JSON file.
    """
    json_path = "training_outputs/evaluation/model_performance.json"

    if not os.path.exists(json_path):
        # Return sensible defaults so the frontend doesn't crash
        # before evaluate_models.py has been run
        return jsonify({
            "error":   "Model performance data not yet computed",
            "message": "Run evaluate_models.py to generate this data",
            "available": False,
        }), 404

    try:
        with open(json_path, "r") as f:
            data = _json.load(f)
        data["available"] = True
        return jsonify(data), 200
    except Exception:
        print(f"[PERF] Error reading JSON:\n{traceback.format_exc()}")
        return jsonify({"error": "Failed to read performance data"}), 500